site_name: Implementación de una Criptomoneda en Hyperledger Fabric
site_description: Guía para implementar una criptomoneda (basada en Tokens ERC-20) en Hyperledger Fabric. Estudio de la posibilidad de aplicar Algoritmos de Consenso personalizados a Hyperledger Fabric.
site_author: David Molina Gámez

theme:
  name: material
  language: es
  
  # Configuración de Colores (Claro / Oscuro)
  palette: 
    # Configuración Modo Claro (Default)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro

    # Configuración Modo Oscuro (Slate)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  # Configuración de Fuente
  font:
    text: Cabin          # Fuente principal solicitada
    code: Roboto Mono    # Fuente para bloques de código (mejor dejar una monoespaciada)

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.top

# Enlazar la hoja de estilos personalizada para el tamaño de letra
extra_css:
  - stylesheets/extra.css

nav:
  - Inicio: index.md
  - Prerrequisitos:
    - Instalación de Docker y Docker-Compose: prerrequisitos/01-docker-y-docker-compose.md
    - Instalación de Go (Golang): prerrequisitos/02-go.md
    - Instalación de Hyperledger Fabric: prerrequisitos/03-hyperledger-fabric.md

  - Gestión de Red:
    - Red Oficial (Test Network): red/01-red-oficial.md
    - Red Personalizada: red/02-red-personal.md

  - Token ERC-20:
    - Conceptos: token/01-concepto-erc20.md
    - Implementación: token/02-implementacion.md
    - Despliegue y Uso:
      - Despliegue (Red Personalizada): token/despliegue/04-despliegue-manual.md
      - Despliegue (Test Network): token/despliegue/03-despliegue-fabric.md
      - Uso del Token: token/05-uso-token.md

  - Consenso Personalizado:
    - Implementación de un algoritmo de consenso personalizado: consenso/investigacion.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      # IMPORTANTE: Definir un estilo compatible
      # 'dracula', 'monokai', 'github-dark' suelen ir bien con Shadcn
      pygments_style: dracula 
  - pymdownx.inlinehilite